version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: statement_converter_backend
    restart: always
    volumes:
      - sqlite_data:/app/data
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: statement_converter_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
